### ISSUE TITLE
"message": "Invalid Audio Format: Not a WAVE file - no RIFF header"

### ISSUE THREAD

**Issue by momohs** [Microsoft/Cognitive-SpeakerRecognition-Android#2]
https://github.com/Microsoft/ProjectOxford-ClientSDK/issues/92 moved here on behalf of @Crasheng

**Comment by momohs** [comment]
Thanks @Crasheng for your comments! Can you please send me the *.wav file that you are trying to enroll? Also, it would be helpful if you share with me how do you record the *.wav file on Android.

**Comment by momohs** [comment]
I'll close this issue due to in-activity! Apparently, it is no longer an issue.
@Crasheng please feel free to re-open if you have any further problems.

**Comment by vishwasrao** [comment]
Hi I am having same issue.
I have recorded audio file and converted to .wav using online tool.
But its giving same error 
"message": "Invalid Audio Format: Not a WAVE file - no RIFF header" 
please find attached audio file.
Also is there way we can convert audio file into specified format or direct streaming options.
[VishwasVoice (2).zip](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Android/files/726323/VishwasVoice.2.zip)

**Comment by sachin-tiwari** [comment]
is this issue resolved?. I am getting the same error

**Comment by vishwasrao** [comment]
Hi,He suggested to use python sample code instead, which is working fine.Check open issue with same problem for link.
Thanks,
Vishwas

**Comment by mohgouda** [comment]
I believe this issue was already addressed [here](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Android/issues/3)

Regards,
Mohamed
Speaker PM

**Comment by bemesquita** [comment]
Still having the same issue!
