### ISSUE TITLE
"message": "Invalid Audio Format: Not a WAVE file - no RIFF header"

### ISSUE THREAD

**Issue by vishwasrao** [Microsoft/Cognitive-SpeakerRecognition-Android#3]
Hi I am having same issue.
I have recorded audio file and converted to .wav using online tool. as there was not a single example showing to record file in correct format.
But its giving same error
[VishwasVoice (2).zip](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Android/files/726359/VishwasVoice.2.zip)

"message": "Invalid Audio Format: Not a WAVE file - no RIFF header"
please find attached audio file.
Also please provide example to  convert audio file into specified format or direct streaming options through android.

**Comment by mohgouda** [comment]
Thanks for reaching out. Can you please send me the audio file, so that I can replicate your case. Send it to mgouda@microsoft.com.

Regards,
Mohamed 
Speaker PM

**Comment by mohgouda** [comment]
Thanks for reaching out. The audio files look good, can you please share with us a code snippet to take a look at?

Regards,
Mohamed
Speaker PM

**Comment by vishwasrao** [comment]
Hi,
Please find below code
I am using sample Python code given in API Documentation.
[Speakerec.txt](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Android/files/754401/Speakerec.txt)

Or even you have working code for Java,Android or any other language,please send me.

Thanks,
Vishwas

**Comment by mohgouda** [comment]
Thanks for your reply. I recommend you using our Python sample app, you can find it [here](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Python). Let me know if you have any further inquiries.

Regards,
Mohamed

**Comment by sumanyurosha** [comment]
How to upload a sound file in the Java sample code...

**Comment by gpt3ch** [comment]
@sumanyurosha Code for uploading file in Java-
File is the wav audio file, which can be created as  follows-

`File f = new File(filepath,"abc.wav");`

```
import org.apache.http.Header;
import org.apache.http.HttpEntity; 
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.FileEntity;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.util.EntityUtils;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.File; 
import java.io.FileNotFoundException;
import java.io.IOException; 

public static void doEnrollment(final Activity contx, String id, File file) {

        try {
            HttpClient httpclient = new DefaultHttpClient();
            String URL = "https://westus.api.cognitive.microsoft.com/spid/v1.0/identificationProfiles/" + id + "/enroll";
            System.out.println("URl 2" + URL);
            HttpPost request = new HttpPost(URL);
            request.setHeader("Content-Type", "multipart/form-data");
            request.setHeader("Ocp-Apim-Subscription-Key", contx.getString(R.string.apikey));
            System.out.println(" data doenroll " + file.getAbsolutePath());
            // Request body
            FileEntity reqEntity = new FileEntity(file, "wav/audio");
            request.setEntity(reqEntity);
            HttpResponse response = httpclient.execute(request);

            System.out.println("response volleyherlper2 " + response);
            HttpEntity entity = response.getEntity();

            if (entity != null) {
                final JSONObject jo = new JSONObject(EntityUtils.toString(entity));
                System.out.println("entity utils 3 " + jo);
                if (jo.getJSONObject("error") != null)
                    contx.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            try {
                                Toast.makeText(contx, "Error! " + jo.getJSONObject("error").getString("message"), Toast.LENGTH_LONG).show();
                            } catch (JSONException e) {
                                e.printStackTrace();
                            }
                        }
                    });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
```

**Comment by M-Sherif-zz** [comment]
@sumanyurosha I assume your question has been answered. Please reach out in case you have any other questions.

**Comment by bramses** [comment]
Running into the same issue using the Python library from: https://github.com/Microsoft/Cognitive-SpeakerRecognition-Python

**Comment by akash0905** [comment]
i am also getting the same issue i am trying with python
**How to upload a sound file in the python sample code... ?**


import http.client, urllib.request, urllib.parse, urllib.error, base64
subscription_key = 'XXXXXXXXXXXXXXXXXXXX'

headers = {
    # Request headers
    'Content-Type': 'multipart/form-data', 'Sample-Rate':'16000',
    'Ocp-Apim-Subscription-Key': subscription_key,
}

params = urllib.parse.urlencode({
    # Request parameters
#    'shortAudio': 'true',
    'identificationProfileId':'530e320b-b309-4445-a597-310bd825af1c',
})


try:
    conn = http.client.HTTPSConnection('speaker-recognition-api.cognitiveservices.azure.com')
    body = open('test.wav','rb')
    conn.request("POST", "/spid/v1.0/identificationProfiles/530e320b-b309-4445-a597-310bd825af1c/enroll?%s" % params, body, headers)
    response = conn.getresponse()
    print(response)
    data = response.read()
    print(data)
    conn.close()
except Exception as e:
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
