### ISSUE TITLE
I am trying to encroll an audio file but return BadRequest

### ISSUE THREAD

**Issue by tokiii** [Microsoft/Cognitive-SpeakerRecognition-Android#6]
Here is my code.

 `
 SpeakerVerificationRestClient speakerVerificationRestClient = new SpeakerVerificationRestClient(MY_KEY);
     try {
                    File file = new File(MY_FILE_PATH);         
                    FileInputStream fileInputStream = new FileInputStream(file);
                    Enrollment enrollment =  speakerVerificationRestClient.enroll(fileInputStream, UUID);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (EnrollmentException e) {
                    e.printStackTrace();
                }
            }
        });`

It's return 
`{  "error": {    "code": "BadRequest",    "message": "SpeechNotRecognized"  }}`

**Comment by M-Sherif-zz** [comment]
Hi @tokiii,

This error means that the service couldn't recognize what is being said in the audio. This might happen for several reasons including: very noisy audio, unclear accent, and non-English speech.
