### ISSUE TITLE
A library uses the same package as this project: com.microsoft.cognitive.speakerrecognition

### ISSUE THREAD

**Issue by Urvika-gola** [Microsoft/Cognitive-SpeakerRecognition-Android#7]
Trying to running this project in Android Studio.
Have added the dependency --   `  compile 'com.microsoft.cognitive:speakerrecognition:1.1.0'`
and added the library by going to the project structure..

When I run this, I am getting the error -- ```

Error:Execution failed for task ':lib:processDebugResources'.
> Error: A library uses the same package as this project: com.microsoft.cognitive.speakerrecognition
```

**Comment by MichZipp** [comment]
I fixed this issue by adding the following line to the gradle.properties:
`android.enableAapt2=false`
